services:
  ui:
    build:
      context: ./ui
    ports:
      - "3001:3000"
    container_name: ui-container

  engine:
    build:
      context: ./engine
    ports:
      - "7700:7700"
    container_name: engine-container
