services:
  ui:
    build:
      context: ./ui
    ports:
      - "4040:80"
    environment:
      - SIGMA_SEARCH_URL=http://localhost:7700
      - SIGMA_SEARCH_AUTH_KEY=a0Mfp5S-WKAQ5_dtAARW3EopM6eij7u-OrrWo4JqTIk
    container_name: ui-container

  engine:
    build:
      context: ./engine
    ports:
      - "7700:7700"
    container_name: engine-container
